# Generated by Django 4.0 on 2022-05-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0002_classnumber_subject_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('classNumber', models.IntegerField()),
            ],
        ),
    ]
