# Generated by Django 4.0 on 2022-05-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0003_currentcourse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='classNumber',
            new_name='с_classNumber',
        ),
        migrations.RemoveField(
            model_name='currentcourse',
            name='name',
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='c_course_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currentcourse',
            name='с_name',
            field=models.TextField(default='a', max_length=60),
            preserve_default=False,
        ),
    ]
