# Generated by Django 4.0 on 2022-05-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0004_rename_classnumber_currentcourse_с_classnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnumber',
            name='number',
            field=models.IntegerField(),
        ),
    ]
