# Generated by Django 4.0 on 2022-05-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edutech_app', '0006_rename_с_name_currentcourse_c_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentcourse',
            old_name='с_classNumber',
            new_name='c_classNumber',
        ),
    ]
